### ISSUE TITLE
Decomposition returns negative values

### ISSUE THREAD

**Issue by JobdePater** [AgroCares/soilptf#25]
the functions for the decomposition returns negative values.  Should'nt that be positive values for decomposition (and negative values for soil carbon build up)?

https://github.com/AgroCares/soilptf/blob/main/R/decomposition.R

**Comment by gerardhros** [comment]
note that the R script has been renamed to cdec in version 0.4.0.
please can you also add a reproducable example?

i see that negative values occur for sptf_cdec1 when inplausible combinations for C and N are given as input (so resulting in extremely high CN ratios). Note the difference in units: g/kg for C and mg/kg for N.

to avoid this, i added an extra interal check in sptf_cec1 on the CN ratios, in branch fix_apr.
checkmate::assert_numeric(cnratio, lower = 1, upper = 100)
